name: "Sync"

on:
  push:
    branches:
      - "main"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to SIGHUP Registry
      uses: docker/login-action@v1
      with:
        registry: reg.sighup.io
        username: ${{ secrets.SIGHUP_REGISTRY_USERNAME }}
        password: ${{ secrets.SIGHUP_REGISTRY_PASSWORD }}
    - name: Install jq
      run: |
        sudo apt-get update && sudo apt-get install -yqq wget
        sudo wget -q https://github.com/mikefarah/yq/releases/download/v4.2.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
    - name: Iterate
      run: |
        ./sync.sh
